name: 'Docker build'

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/workflows/**'
      - 'examples/**'
    branches:
      - ha-addon
      - main
    tags:
      - '*.*.*'
  workflow_dispatch:
env:
  IMAGE_NAME: rtlamr2mqtt

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            irakhlin/rtlamr2mqtt
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=sha
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/i386,linux/arm64,linux/arm/v7,linux/arm/v6
          push:  ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.actor }}/rtlamr2mqtt:ha-addon
          labels: ${{ steps.meta.outputs.labels }}
